CORES = fbalpha2012-neogeo mame2003 handy stella2014 a5200 prosystem gw fuse crocods

###############################

# optional core vars
# *_REPO=
# *_HASH=
# *_CORE=
# *_FLAGS=
# *_MAKEFILE=
# *_BUILD_PATH=

fbalpha2012-neogeo_REPO = https://github.com/libretro/fbalpha2012_neogeo
fbalpha2012-neogeo_CORE = fbalpha2012_neogeo_libretro.so

mame2003_REPO = https://github.com/libretro/mame2003-libretro
mame2003_CORE = mame2003_libretro.so

handy_REPO = https://github.com/libretro/libretro-handy
handy_CORE = handy_libretro.so

stella2014_REPO = https://github.com/libretro/stella2014-libretro
stella2014_CORE = stella2014_libretro.so

a5200_REPO = https://github.com/libretro/a5200
a5200_CORE = a5200_libretro.so

prosystem_REPO = https://github.com/libretro/prosystem-libretro
prosystem_CORE = prosystem_libretro.so

gw_REPO = https://github.com/libretro/gw-libretro
gw_CORE = gw_libretro.so

fuse_REPO = https://github.com/libretro/fuse-libretro
fuse_CORE = fuse_libretro.so

crocods_REPO = https://github.com/libretro/libretro-crocods
crocods_CORE = crocods_libretro.so

###############################

include ../../all/cores/makefile