CORES = fbalpha2012-neogeo mame2003 handy

###############################

# optional core vars
# *_REPO=
# *_HASH=
# *_CORE=
# *_FLAGS=
# *_MAKEFILE=
# *_BUILD_PATH=

fbalpha2012-neogeo_REPO = https://github.com/libretro/fbalpha2012_neogeo
fbalpha2012-neogeo_CORE = fbalpha2012_neogeo_libretro.so

mame2003_REPO = https://github.com/libretro/mame2003-libretro
mame2003_CORE = mame2003_libretro.so

handy_REPO = https://github.com/libretro/libretro-handy
handy_CORE = handy_libretro.so

###############################

include ../../all/cores/makefile