.PHONY: cores

cores:
	cp ./cores/output/fbalpha2012_neogeo_libretro.so ../../build/EXTRAS/Emus/m17/NG.pak
	cp ./cores/output/mame2003_libretro.so ../../build/EXTRAS/Emus/m17/MAME.pak
	cp ./cores/output/handy_libretro.so ../../build/EXTRAS/Emus/m17/LYNX.pak
	cp ./cores/output/stella2014_libretro.so ../../build/EXTRAS/Emus/m17/A2600.pak
	cp ./cores/output/a5200_libretro.so ../../build/EXTRAS/Emus/m17/A5200.pak
	cp ./cores/output/prosystem_libretro.so ../../build/EXTRAS/Emus/m17/A7800.pak
	cp ./cores/output/gw_libretro.so ../../build/EXTRAS/Emus/m17/GW.pak
	cp ./cores/output/fuse_libretro.so ../../build/EXTRAS/Emus/m17/ZXS.pak
	cp ./cores/output/crocods_libretro.so ../../build/EXTRAS/Emus/m17/ACPC.pak