name: Makefile CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: 'Make'
      run: make all

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: release
        path: releases
        retention-days: 30
